export { default as Layout } from './layout';
export { default as Loader } from './loader';
export { default as Hero } from './sections/hero';
export {default as Nav}from './nav';
export {default as Menu}from './menu';
export { default as Social } from './social';
export { default as TechCategories } from './techCategories';
export { default as About } from './sections/about';
// export { default as Jobs } from './sections/jobs';
// export { default as Featured } from './sections/featured';
// export { default as Projects } from './sections/projects';
// export { default as Contact } from './sections/contact';
